"""F-14: PDF Report generation using WeasyPrint + Jinja2."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from uuid import UUID

from jinja2 import Environment, FileSystemLoader
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.threat import Threat
from app.models.threat_model import ThreatModel
from app.services.compliance_service import lookup_controls_batch
from app.schemas.threat import ThreatResponse

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"

METHODOLOGY_TEXT = (
    "This threat model was generated by ThreatGenix using the STRIDE methodology "
    "(Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, "
    "Elevation of Privilege). Threats were identified through a combination of "
    "deterministic rules applied to the system's Data Flow Diagram and AI-powered "
    "contextual analysis. Compliance mappings reference NIST 800-53 controls. "
    "This report should be reviewed by a qualified security professional before "
    "being entered into the organization's risk register."
)


async def generate_report(
    db: AsyncSession,
    threat_model_id: UUID,
    dfd_image_base64: str = "",
) -> bytes:
    """Load threat model data, render HTML via Jinja2, convert to PDF via WeasyPrint.

    Returns PDF bytes.
    """
    # 1. Load threat model
    result = await db.execute(
        select(ThreatModel).where(ThreatModel.id == threat_model_id)
    )
    threat_model = result.scalar_one_or_none()
    if threat_model is None:
        raise ValueError(f"Threat model {threat_model_id} not found")

    # 2. Load threats (accepted + open only, not dismissed), sorted by display_id
    threats_result = await db.execute(
        select(Threat)
        .where(
            Threat.threat_model_id == threat_model_id,
            Threat.status.in_(["Open", "Accepted"]),
        )
        .order_by(Threat.display_id)
    )
    threats = list(threats_result.scalars().all())

    # 3. Lookup compliance controls for all threats
    controls_map = await lookup_controls_batch(db, threats)

    # 4. Build template context
    threat_dicts = []
    compliance_by_threat = []
    for t in threats:
        resp = ThreatResponse.model_validate(t)
        resp.compliance_controls = controls_map.get(t.id, [])
        threat_dicts.append({
            "display_id": resp.display_id,
            "stride_category": resp.stride_category,
            "severity": resp.severity,
            "description": resp.description,
            "source": resp.source,
            "status": resp.status,
        })
        compliance_by_threat.append({
            "display_id": resp.display_id,
            "stride_category": resp.stride_category,
            "controls": [
                {"nist_control_id": c.nist_control_id, "nist_control_name": c.nist_control_name}
                for c in resp.compliance_controls
            ],
        })

    now = datetime.now(timezone.utc)
    context = {
        "system_name": threat_model.system_name,
        "description": threat_model.description,
        "data_classification": threat_model.data_classification,
        "created_at": threat_model.created_at.strftime("%Y-%m-%d %H:%M UTC")
        if threat_model.created_at
        else "N/A",
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "dfd_image_base64": dfd_image_base64,
        "threats": threat_dicts,
        "compliance_by_threat": compliance_by_threat,
        "methodology_text": METHODOLOGY_TEXT,
    }

    # 5. Render HTML
    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), autoescape=True)
    template = env.get_template("report.html")
    html_content = template.render(**context)

    # 6. Convert to PDF via WeasyPrint
    from weasyprint import HTML

    pdf_bytes = HTML(string=html_content).write_pdf()

    logger.info(
        "pdf_report_generated threat_model_id=%s threats=%d size_bytes=%d",
        threat_model_id,
        len(threats),
        len(pdf_bytes),
    )

    return pdf_bytes
